### ISSUE TITLE
Unload Dll

### ISSUE THREAD

**Issue by nt153133** [Mbucari/InjectDotnet#2]
I could have missed it but I haven't found any code to unload a library after it's injected. Even with the sample project once you close the form you the dll file stays in use until the target process has been closed. Ie. you can't test mutiple versions on the same running exe since the injected.dll and InjectDotnet.NativeHelper dll are always in use. Is there any ways around this?

**Comment by Mbucari** [comment]
@nt153133 unfortunately unloading is not supported by hostfxr.  See [this open issue](https://github.com/dotnet/runtime/issues/70229)

However, that same issue makes a suggestion for a possible work around:

> There are possible workaround which are a bit complicated. You could use a small helper assembly which is the one your native library loads and through it load other assemblies. Since the helper assembly is managed code, it can create a new load context into which it loads other assemblies and it could also unload such load context.
